-- ========================================================
-- DON GUTO INTRANET - TABLA DE HORARIOS ROTATIVOS SEMANALES
-- ========================================================

CREATE TABLE IF NOT EXISTS horarios_semanales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    hora_entrada VARCHAR(50) NOT NULL, -- ej. "07:00", "14:30", "OFF"
    hora_salida VARCHAR(50) NOT NULL,  -- ej. "15:00", "22:30", "OFF"
    store VARCHAR(100) NOT NULL,       -- ej. "28 de Julio Miraflores", "Barranco"
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (username, fecha)
);

-- Habilitar índices para optimizar la velocidad de búsqueda
CREATE INDEX IF NOT EXISTS idx_horarios_fecha ON horarios_semanales(fecha);
CREATE INDEX IF NOT EXISTS idx_horarios_username ON horarios_semanales(username);
