import pg8000
import ssl

def test_connect(host, port, user, password, database, use_ssl=True, verify_ssl=True):
    print(f"Testing port {port} (SSL={use_ssl}, Verify={verify_ssl})...")
    try:
        ssl_ctx = None
        if use_ssl:
            ssl_ctx = ssl.create_default_context()
            if not verify_ssl:
                ssl_ctx.check_hostname = False
                ssl_ctx.verify_mode = ssl.CERT_NONE
        
        conn = pg8000.connect(
            host=host,
            port=port,
            user=user,
            password=password,
            database=database,
            ssl_context=ssl_ctx
        )
        return conn
    except Exception as e:
        print(f"Failed on port {port}: {e}")
        return None

def main():
    host = "db.jchpxowbxxfrivrloqkg.supabase.co"
    user = "postgres"
    password = "TCRXdgcuaVQkHu2r"
    database = "postgres"

    conn = None
    for port in [5432, 6543]:
        for verify in [True, False]:
            conn = test_connect(host, port, user, password, database, use_ssl=True, verify_ssl=verify)
            if conn:
                break
        if conn:
            break
            
    if not conn:
        print("Could not establish a connection on any port/configuration.")
        return

    print("Connected successfully!")
    try:
        cursor = conn.cursor()
        
        # 1. CREATE TABLE
        print("Creating table 'horarios_semanales'...")
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS horarios_semanales (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
            fecha DATE NOT NULL,
            hora_entrada VARCHAR(50) NOT NULL,
            hora_salida VARCHAR(50) NOT NULL,
            store VARCHAR(100) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (username, fecha)
        );
        """
        cursor.execute(create_table_sql)
        print("Table creation complete.")

        # 2. CREATE INDEXES
        print("Creating indexes...")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_horarios_fecha ON horarios_semanales(fecha);")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_horarios_username ON horarios_semanales(username);")
        print("Indexes creation complete.")

        conn.commit()
        print("Changes committed successfully!")
        
        # Verify columns and schema
        cursor.execute("SELECT tablename FROM pg_tables WHERE schemaname = 'public';")
        tables = cursor.fetchall()
        print("Tables in public schema:", [t[0] for t in tables])

        cursor.close()
        conn.close()
        print("Done!")

    except Exception as e:
        print("Error during SQL execution:", e)

if __name__ == "__main__":
    main()
