import pg from 'pg';

export default async function handler(req, res) {
  // Direct connection credentials using Supavisor Pooler for sa-east-1 region
  const connectionString = "postgres://postgres.jchpxowbxxfrivrloqkg:TCRXdgcuaVQkHu2r@aws-0-sa-east-1.pooler.supabase.com:6543/postgres";
  
  const client = new pg.Client({
    connectionString,
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    await client.connect();
    
    // 1. CREATE TABLE
    const createTableSql = `
      CREATE TABLE IF NOT EXISTS horarios_semanales (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username VARCHAR(100) NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
          fecha DATE NOT NULL,
          hora_entrada VARCHAR(50) NOT NULL,
          hora_salida VARCHAR(50) NOT NULL,
          store VARCHAR(100) NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          UNIQUE (username, fecha)
      );
    `;
    await client.query(createTableSql);

    // 2. CREATE INDEXES
    await client.query("CREATE INDEX IF NOT EXISTS idx_horarios_fecha ON horarios_semanales(fecha);");
    await client.query("CREATE INDEX IF NOT EXISTS idx_horarios_username ON horarios_semanales(username);");

    // Verify tables
    const result = await client.query("SELECT tablename FROM pg_tables WHERE schemaname = 'public';");
    const tables = result.rows.map(r => r.tablename);

    await client.end();

    return res.status(200).json({
      status: 'success',
      message: 'Table horarios_semanales and indexes created successfully!',
      tables
    });

  } catch (err) {
    try {
      await client.end();
    } catch (e) {}
    
    return res.status(500).json({
      status: 'error',
      message: err.message
    });
  }
}
