import pg from 'pg';

export default async function handler(req, res) {
  const hosts = [
    "aws-0-sa-east-1.pooler.supabase.com",
    "aws-1-sa-east-1.pooler.supabase.com"
  ];
  
  let success = false;
  let lastError = null;
  let activeHost = "";
  let tables = [];

  for (const host of hosts) {
    const connectionString = `postgres://postgres.jchpxowbxxfrivrloqkg:TCRXdgcuaVQkHu2r@${host}:6543/postgres`;
    const client = new pg.Client({
      connectionString,
      ssl: {
        rejectUnauthorized: false
      }
    });

    try {
      console.log(`Trying to connect to ${host}...`);
      await client.connect();
      activeHost = host;
      
      // 1. CREATE TABLE
      const createTableSql = `
        CREATE TABLE IF NOT EXISTS horarios_semanales (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
            fecha DATE NOT NULL,
            hora_entrada VARCHAR(50) NOT NULL,
            hora_salida VARCHAR(50) NOT NULL,
            store VARCHAR(100) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (username, fecha)
        );
      `;
      await client.query(createTableSql);

      // 2. CREATE INDEXES
      await client.query("CREATE INDEX IF NOT EXISTS idx_horarios_fecha ON horarios_semanales(fecha);");
      await client.query("CREATE INDEX IF NOT EXISTS idx_horarios_username ON horarios_semanales(username);");

      // Verify tables
      const result = await client.query("SELECT tablename FROM pg_tables WHERE schemaname = 'public';");
      tables = result.rows.map(r => r.tablename);

      await client.end();
      success = true;
      break; // Success! Exit loop

    } catch (err) {
      console.error(`Failed connecting to ${host}:`, err.message);
      lastError = err.message;
      try {
        await client.end();
      } catch (e) {}
    }
  }

  if (success) {
    return res.status(200).json({
      status: 'success',
      message: `Table horarios_semanales and indexes created successfully on host ${activeHost}!`,
      tables
    });
  } else {
    return res.status(500).json({
      status: 'error',
      message: `Failed to connect/execute on all pooler hosts. Last error: ${lastError}`
    });
  }
}
